Repository CS2103JAN2018-F11-B4/main, pull requests merged in 2018-04, with the labels that each got.

#82 Add Order feature and update the AddCommand
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high

#98 Collate code
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/main/java/seedu/address/model/dish/Name.java
  src/main/java/seedu/address/model/dish/Price.java
  src/main/java/seedu/address/model/dish/exceptions/DishNotFoundException.java
  src/main/java/seedu/address/model/person/Halal.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Vegetarian.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.high, severity.high

#142 Build up the checking process for whether ordered dish is available
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/MenuChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/Menu.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/dish/Dish.java
  src/main/java/seedu/address/model/dish/Price.java
  src/main/java/seedu/address/model/dish/exceptions/DishNotFoundException.java
  src/main/java/seedu/address/model/person/Order.java
  src/main/java/seedu/address/storage/MenuStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlMenuStorage.java
  src/main/java/seedu/address/storage/XmlSerializableMenu.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/PathCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoableCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, severity.high

#149 Add deleteOrder feature and completeOrder feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/CompleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CompleteOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteOrderCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.enhancement

#155 Update the name and the icon
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Delivery_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.high, severity.high

#164 Add more commands
  collated/functional/Wuhao-ooo.md
  collated/functional/ZacZequn.md
  collated/functional/ZhangYijiong.md
  collated/test/ZacZequn.md
  collated/test/ZhangYijiong.md
  src/main/java/seedu/address/commons/events/ui/LoadPageChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/PersonPanelPathChangedEvent.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/CompleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/LoadCommand.java
  src/main/java/seedu/address/logic/commands/ProcessMoreCommand.java
  src/main/java/seedu/address/logic/commands/ProcessNextCommand.java
  src/main/java/seedu/address/logic/commands/ProcessOrderCommand.java
  src/main/java/seedu/address/logic/commands/TagOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/LoadCommandParser.java
  src/main/java/seedu/address/logic/parser/ProcessMoreCommandParser.java
  src/main/java/seedu/address/logic/parser/ProcessNextCommandParser.java
  src/main/java/seedu/address/logic/parser/ProcessOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/TagOrderCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/queue/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/default.html
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: type.epic

#167 Update all the relevant documentations
  collated/functional/Wuhao-ooo.md
  collated/functional/ZacZequn.md
  collated/functional/ZhangYijiong.md
  collated/test/Wuhao-ooo.md
  collated/test/ZacZequn.md
  collated/test/ZhangYijiong.md
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/menu_fig_1.png
  docs/images/menu_fig_2.png
  docs/images/menu_fig_3.png
  docs/team/zhangzequn.adoc
Labels: priority.high
